AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.8

  Sample SAM Template for STAC_to_geoCore

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900

Resources:
  STACtoGeoCoreFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Events:
        STACtoGeoCore:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /stac_to_geocore
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./stac_to_geocore
      DockerTag: python3.8-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  STACtoGeoCoreApi:
    Description: "API Gateway endpoint URL for Prod stage for STAC to GeoCore function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/stac_to_geocore/"
  HelloWorldFunction:
    Description: "STAC to GeoCore Lambda Function ARN"
    Value: !GetAtt STACtoGeoCoreFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for STAC to GeoCore function"
    Value: !GetAtt STACtoGeoCoreFunctionRole.Arn
